
server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: rootpassword
  jpa:
    properties.hibernate-dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000